# Generated by Django 3.0.5 on 2020-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('core_num', models.IntegerField()),
                ('core_frequency', models.FloatField()),
                ('ram_volume', models.IntegerField()),
                ('rom_volume', models.IntegerField()),
                ('lte_exists', models.BooleanField()),
                ('wifi_version', models.CharField(max_length=255)),
                ('bluetooth_version', models.CharField(max_length=255)),
                ('nfc_exists', models.BooleanField()),
            ],
        ),
    ]
