# Generated by Django 3.0.5 on 2020-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='bluetooth_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='core_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='core_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='nfc_exists',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='rom_volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='wifi_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
